export const travelTables = [
    {
        key: 'starshiptravelevent',
        title: 'Starship Tavel Event',
        tables: {
            default: [
                { "label": "Asteroids", "weight": 8 },
                { "label": "Navigation trouble", "weight": 5 },
                { "label": "Raided", "weight": 5 },
                { "label": "Deep space wreckage", "weight": 8 },
                { "label": "Drive trouble", "weight": 4 },
                { "label": "Down-time", "weight": 9 },
                { "label": "Distress call", "weight": 6 },
                { "label": "Patrol ship", "weight": 6 },
                { "label": "Cosmic phenomenon", "weight": 3 },
                { "label": "Escape pod", "weight": 7 },
                { "label": "Accident", "weight": 6 },
                { "label": "Travel-time", "weight": 9 },
                { "label": "Uneventful trip", "weight": 10 },
                { "label": "Time to reflect", "weight": 6 },
                { "label": "Time to read a book", "weight": 4 },
                { "label": "Locked in the library data by night", "weight": 5 },
            ]
        }
    },   
    {
        key: 'newworldtraits',
        title: 'New World Traits',
        tables: {
            default: [
                { "label": "Haze", "weight": 4 },
                { "label": "Overgrown", "weight": 3 },
                { "label": "Warzone", "weight": 2 },
                { "label": "Heavily enforced", "weight": 2 },
                { "label": "Rampant crime", "weight": 2 },
                { "label": "Invasion risk", "weight": 2 },
                { "label": "Imminent invasion", "weight": 2 },
                { "label": "Lacks starship facility", "weight": 2 },
                { "label": "Easy recruiting", "weight": 2 },
                { "label": "Medical science", "weight": 2 },
                { "label": "Technical knowledge", "weight": 2 },
                { "label": "Opportunities", "weight": 2 },
                { "label": "Booming economy", "weight": 3 },
                { "label": "Busy markets", "weight": 3 },
                { "label": "Bureaucratic mess", "weight": 2 },
                { "label": "Restricted education", "weight": 2 },
                { "label": "Expensive education", "weight": 2 },
                { "label": "Travel restricted", "weight": 3 },
                { "label": "Unity safe sector", "weight": 2 },
                { "label": "Gloom", "weight": 3 },
                { "label": "Bot manufacturing", "weight": 2 },
                { "label": "Fuel refinery", "weight": 3 },
                { "label": "Alien species restricted", "weight": 2 },
                { "label": "Weapon licensing", "weight": 2 },
                { "label": "Import restrictions", "weight": 2 },
                { "label": "Military outpost", "weight": 2 },
                { "label": "Dangerous", "weight": 3 },
                { "label": "Shipyards", "weight": 2 },
                { "label": "Barren", "weight": 2 },
                { "label": "Vendetta system", "weight": 2 },
                { "label": "Free trade zone", "weight": 3 },
                { "label": "Corporate state", "weight": 2 },
                { "label": "Adventurous Population", "weight": 2 },
                { "label": "Frozen", "weight": 3 },
                { "label": "Flat", "weight": 2 },
                { "label": "Fuel shortage", "weight": 3 },
                { "label": "Reflective dust", "weight": 2 },
                { "label": "High cost", "weight": 3 },
                { "label": "Interdiction", "weight": 2 },
                { "label": "Null zone", "weight": 2 },
                { "label": "Crystals", "weight": 3 },
                { "label": "Fog", "weight": 4 },
            ]
        }
    },   
]