export const battleTables = [
    {
        key: 'deploymentconditions',
        title: 'Deployment Conditions',
        sequence: ["default", "rival", "quest"],
        tables: {
            default: [
                { "label": "None", "weight": 40 },
                { "label": "Small encounter", "weight": 5 },
                { "label": "Poor visibility", "weight": 5 },
                { "label": "Brief engagement", "weight": 5 },
                { "label": "Toxic environment", "weight": 5 },
                { "label": "Surprise encounter", "weight": 5 },
                { "label": "Delayed", "weight": 10 },
                { "label": "Slippery ground", "weight": 5 },
                { "label": "Bitter struggle", "weight": 5 },
                { "label": "Caught off guard", "weight": 5 },
                { "label": "Gloomy", "weight": 10 },
            ],
            rival: [
                { "label": "None", "weight": 10 },
                { "label": "Small encounter", "weight": 5 },
                { "label": "Poor visibility", "weight": 5 },
                { "label": "Brief engagement", "weight": 5 },
                { "label": "Toxic environment", "weight": 5 },
                { "label": "Surprise encounter", "weight": 15 },
                { "label": "Delayed", "weight": 5 },
                { "label": "Slippery ground", "weight": 10 },
                { "label": "Bitter struggle", "weight": 15 },
                { "label": "Caught off guard", "weight": 15 },
                { "label": "Gloomy", "weight": 10 },
            ],
            quest: [
                { "label": "None", "weight": 5 },
                { "label": "Small encounter", "weight": 5 },
                { "label": "Poor visibility", "weight": 15 },
                { "label": "Brief engagement", "weight": 5 },
                { "label": "Toxic environment", "weight": 10 },
                { "label": "Surprise encounter", "weight": 10 },
                { "label": "Delayed", "weight": 10 },
                { "label": "Slippery ground", "weight": 5 },
                { "label": "Bitter struggle", "weight": 15 },
                { "label": "Caught off guard", "weight": 10 },
                { "label": "Gloomy", "weight": 10 },
            ],

        }
    },
    {
        key: 'notablesights',
        title: 'Notable Sights',
        sequence: ["default", "rival", "quest"],
        tables: {
            default: [
                { "label": "Nothing special", "weight": 20 },
                { "label": "Documentation", "weight": 10 },
                { "label": "Priority target", "weight": 10 },
                { "label": "Loot cache", "weight": 10 },
                { "label": "Shiny bits", "weight": 10 },
                { "label": "Really shiny bits", "weight": 10 },
                { "label": "Person of interest", "weight": 10 },
                { "label": "Peculiar item", "weight": 10 },
                { "label": "Curious Item", "weight": 10 },
            ],
            rival: [
                { "label": "Nothing special", "weight": 40 },
                { "label": "Documentation", "weight": 10 },
                { "label": "Priority target", "weight": 10 },
                { "label": "Loot cache", "weight": 10 },
                { "label": "Shiny bits", "weight": 5 },
                { "label": "Really shiny bits", "weight": 5 },
                { "label": "Person of interest", "weight": 10 },
                { "label": "Peculiar item", "weight": 5 },
                { "label": "Curious Item", "weight": 5 },
            ],
            quest: [
                { "label": "Nothing special", "weight": 10 },
                { "label": "Documentation", "weight": 15 },
                { "label": "Priority target", "weight": 10 },
                { "label": "Loot cache", "weight": 15 },
                { "label": "Shiny bits", "weight": 5 },
                { "label": "Really shiny bits", "weight": 10 },
                { "label": "Person of interest", "weight": 15 },
                { "label": "Peculiar item", "weight": 10 },
                { "label": "Curious Item", "weight": 10 },
            ],

        }
    },
    {
        key: 'missionobjective',
        title: 'Mission Objective',
        sequence: ["patron", "opportunity", "quest"],
        tables: {
            patron: [
                { "label": "Deliver", "weight": 2 },
                { "label": "Eliminate", "weight": 1 },
                { "label": "Move Through", "weight": 2 },
                { "label": "Secure", "weight": 2 },
                { "label": "Protect", "weight": 1 },
                { "label": "Fight Off", "weight": 2 },
            ],
            opportunity: [
                { "label": "Move Through", "weight": 2 },
                { "label": "Deliver", "weight": 2 },
                { "label": "Access", "weight": 2 },
                { "label": "Patrol", "weight": 2 },            
                { "label": "Fight Off", "weight": 2 },
            ],
            quest: [
                { "label": "Move Through", "weight": 2 },
                { "label": "Search", "weight": 2 },
                { "label": "Defend", "weight": 2 },
                { "label": "Acquire", "weight": 2 },            
                { "label": "Fight Off", "weight": 2 },
            ],

        }
    },
    {
        key: 'rivalattack',
        title: 'Rival Attack',        
        tables: {
            weaponA: [
                { "label": "Ambush", "weight": 1 },
                { "label": "Brought friends", "weight": 2 },
                { "label": "Showdown", "weight": 2 },
                { "label": "Assault", "weight": 1 },
                { "label": "Raid", "weight": 1 },                
            ],            
        }
    },
    {
        key: 'enemyencountercategory',
        title: 'Enemy Encounter Category',
        sequence: ["patron", "opportunity", "quest", "unknownrival"],
        tables: {
            patron: [
                { "label": "Criminal Elements", "subtable": "criminalelements", "weight": 25 },
                { "label": "Hired Muscle", "subtable": "hiredmuscle", "weight": 25 },
                { "label": "Interested Parties", "subtable": "interestedparties", "weight": 25 },
                { "label": "Roving Threats", "subtable": "rovingthreats", "weight": 25 },
            ],
            opportunity: [
                { "label": "Criminal Elements", "subtable": "criminalelements", "weight": 30 },
                { "label": "Hired Muscle", "subtable": "hiredmuscle", "weight": 30 },
                { "label": "Interested Parties", "subtable": "interestedparties", "weight": 20 },
                { "label": "Roving Threats", "subtable": "rovingthreats", "weight": 20 },
            ],
            quest: [
                { "label": "Criminal Elements", "subtable": "criminalelements", "weight": 15 },
                { "label": "Hired Muscle", "subtable": "hiredmuscle", "weight": 25 },
                { "label": "Interested Parties", "subtable": "interestedparties", "weight": 30 },
                { "label": "Roving Threats", "subtable": "rovingthreats", "weight": 30 },
            ],
            unknownrival: [
                { "label": "Criminal Elements", "subtable": "criminalelements", "weight": 50 },
                { "label": "Hired Muscle", "subtable": "hiredmuscle", "weight": 30 },
                { "label": "Interested Parties", "subtable": "rovingthreats", "weight": 20 },               
            ],
            criminalelements: [                
                { "label": "Gangers", "description": "{ \"numbers\": 2, \"weapons\": \"1A\" }", "weight": 10 },
                { "label": "Punks", "description": "{ \"numbers\": 3, \"weapons\": \"1A\" }", "weight": 9 },
                { "label": "Raiders", "description": "{ \"numbers\": 1, \"weapons\": \"2A\" }", "weight": 8 },
                { "label": "Cultists", "description": "{ \"numbers\": 2, \"weapons\": \"1A\" }", "weight": 7 },
                { "label": "Psychos", "description": "{ \"numbers\": 2, \"weapons\": \"1B\" }", "weight": 9 },
                { "label": "Brat Gang", "description": "{ \"numbers\": 2, \"weapons\": \"2C\" }", "weight": 5 },
                { "label": "Gene Renegade", "description": "{ \"numbers\": 1, \"weapons\": \"1B\" }", "weight": 3 },
                { "label": "Anarchists", "description": "{ \"numbers\": 2, \"weapons\": \"2B\" }", "weight": 6 },
                { "label": "Pirates", "description": "{ \"numbers\": 2, \"weapons\": \"2A\" }", "weight": 7 },
                { "label": "K'Erin Outlaws", "description": "{ \"numbers\": 1, \"weapons\": \"2A\" }", "weight": 7 },
                { "label": "Skulker Brigands", "description": "{ \"numbers\": 3, \"weapons\": \"1B\" }", "weight": 8 },
                { "label": "Tech Gangers", "description": "{ \"numbers\": 1, \"weapons\": \"3C\" }", "weight": 4 },
                { "label": "Starport Scum", "description": "{ \"numbers\": 3, \"weapons\": \"1A\" }", "weight": 7 },
                { "label": "Hulker Gang", "description": "{ \"numbers\": 0 , \"weapons\": \"1A\" }", "weight": 4 },
                { "label": "Gun Slingers", "description": "{ \"numbers\": 1, \"weapons\": \"1B\" }", "weight": 6 },
            ],
            hiredmuscle: [                
                { "label": "Unkown Mercs", "description": "{ \"numbers\": 0, \"weapons\": \"2B\" }", "weight": 15 },
                { "label": "Enforcers", "description": "{ \"numbers\": 0, \"weapons\": \"2A\" }", "weight": 12 },
                { "label": "Guild Troops", "description": "{ \"numbers\": 0, \"weapons\": \"2C\" }", "weight": 8 },
                { "label": "Roid-gangers", "description": "{ \"numbers\": 1, \"weapons\": \"1A\" }", "weight": 5 },
                { "label": "Black Ops Team", "description": "{ \"numbers\": 0, \"weapons\": \"3A\" }", "weight": 3 },
                { "label": "War Bots", "description": "{ \"numbers\": 0, \"weapons\": \"3C\" }", "weight": 4 },
                { "label": "Secret Agents", "description": "{ \"numbers\": 0, \"weapons\": \"2C\" }", "weight": 4 },
                { "label": "Assassins", "description": "{ \"numbers\": 0, \"weapons\": \"1B\" }", "weight": 3 },
                { "label": "Feral Mercenaries", "description": "{ \"numbers\": 2, \"weapons\": \"2B\" }", "weight": 6 },
                { "label": "Skulker Mercenaries", "description": "{ \"numbers\": 3, \"weapons\": \"2C\" }", "weight": 5 },
                { "label": "Corporate Security", "description": "{ \"numbers\": 1, \"weapons\": \"2B\" }", "weight": 10 },
                { "label": "Unity Grunts", "description": "{ \"numbers\": 1, \"weapons\": \"2C\" }", "weight": 5 },
                { "label": "Security Bots", "description": "{ \"numbers\": 1, \"weapons\": \"2A\" }", "weight": 6 },
                { "label": "Black Dragon Mercs", "description": "{ \"numbers\": 1 , \"weapons\": \"2C\" }", "weight": 5 },
                { "label": "Rage Lizard Mercs", "description": "{ \"numbers\": 0, \"weapons\": \"3B\" }", "weight": 5 },
                { "label": "Blood Storm Mercs", "description": "{ \"numbers\": 0, \"weapons\": \"2B\" }", "weight": 5 },
            ],
            interestedparties: [                
                { "label": "Gangers", "description": "{ \"numbers\": 2, \"weapons\": \"1A\" }", "weight": 10 },
                { "label": "Punks", "description": "{ \"numbers\": 3, \"weapons\": \"1A\" }", "weight": 9 },
                { "label": "Raiders", "description": "{ \"numbers\": 1, \"weapons\": \"2A\" }", "weight": 8 },
                { "label": "Cultists", "description": "{ \"numbers\": 2, \"weapons\": \"1A\" }", "weight": 7 },
                { "label": "Psychos", "description": "{ \"numbers\": 2, \"weapons\": \"1B\" }", "weight": 9 },
                { "label": "Brat Gang", "description": "{ \"numbers\": 2, \"weapons\": \"2C\" }", "weight": 5 },
                { "label": "Gene Renegade", "description": "{ \"numbers\": 1, \"weapons\": \"1B\" }", "weight": 3 },
                { "label": "Anarchists", "description": "{ \"numbers\": 2, \"weapons\": \"2B\" }", "weight": 6 },
                { "label": "Pirates", "description": "{ \"numbers\": 2, \"weapons\": \"2A\" }", "weight": 7 },
                { "label": "K'Erin Outlaws", "description": "{ \"numbers\": 1, \"weapons\": \"2A\" }", "weight": 7 },
                { "label": "Skulker Brigands", "description": "{ \"numbers\": 3, \"weapons\": \"1B\" }", "weight": 8 },
                { "label": "Tech Gangers", "description": "{ \"numbers\": 1, \"weapons\": \"3C\" }", "weight": 4 },
                { "label": "Starport Scum", "description": "{ \"numbers\": 3, \"weapons\": \"1A\" }", "weight": 7 },
                { "label": "Hulker Gang", "description": "{ \"numbers\": 0 , \"weapons\": \"1A\" }", "weight": 4 },
                { "label": "Gun Slingers", "description": "{ \"numbers\": 1, \"weapons\": \"1B\" }", "weight": 6 },
            ],
            rovingthreats: [                
                { "label": "Gangers", "description": "{ \"numbers\": 2, \"weapons\": \"1A\" }", "weight": 10 },
                { "label": "Punks", "description": "{ \"numbers\": 3, \"weapons\": \"1A\" }", "weight": 9 },
                { "label": "Raiders", "description": "{ \"numbers\": 1, \"weapons\": \"2A\" }", "weight": 8 },
                { "label": "Cultists", "description": "{ \"numbers\": 2, \"weapons\": \"1A\" }", "weight": 7 },
                { "label": "Psychos", "description": "{ \"numbers\": 2, \"weapons\": \"1B\" }", "weight": 9 },
                { "label": "Brat Gang", "description": "{ \"numbers\": 2, \"weapons\": \"2C\" }", "weight": 5 },
                { "label": "Gene Renegade", "description": "{ \"numbers\": 1, \"weapons\": \"1B\" }", "weight": 3 },
                { "label": "Anarchists", "description": "{ \"numbers\": 2, \"weapons\": \"2B\" }", "weight": 6 },
                { "label": "Pirates", "description": "{ \"numbers\": 2, \"weapons\": \"2A\" }", "weight": 7 },
                { "label": "K'Erin Outlaws", "description": "{ \"numbers\": 1, \"weapons\": \"2A\" }", "weight": 7 },
                { "label": "Skulker Brigands", "description": "{ \"numbers\": 3, \"weapons\": \"1B\" }", "weight": 8 },
                { "label": "Tech Gangers", "description": "{ \"numbers\": 1, \"weapons\": \"3C\" }", "weight": 4 },
                { "label": "Starport Scum", "description": "{ \"numbers\": 3, \"weapons\": \"1A\" }", "weight": 7 },
                { "label": "Hulker Gang", "description": "{ \"numbers\": 0 , \"weapons\": \"1A\" }", "weight": 4 },
                { "label": "Gun Slingers", "description": "{ \"numbers\": 1, \"weapons\": \"1B\" }", "weight": 6 },
            ],
        }
    },
    {
        key: 'enemyweapons',
        title: 'Enemy Weapons',
        sequence: ["weapon1", "weapon2", "weapon3"],
        tables: {
            weapon1: [
                { "label": "Scrap Pistol", "weight": 1 },
                { "label": "Hand Gun", "weight": 1 },
                { "label": "Colony Rifle", "weight": 1 },
                { "label": "Military Rifle", "weight": 1 },
                { "label": "Scrap pistol + Blade", "weight": 1 },
                { "label": "Shotgun", "weight": 1 },
            ],
            weapon2: [
                { "label": "Colony Rifle", "weight": 1 },
                { "label": "Military Rifle", "weight": 3 },
                { "label": "Hand laser", "weight": 1 },
                { "label": "Infantry laser", "weight": 1 },
            ],
            weapon3: [
                { "label": "Hand laser", "weight": 2 },
                { "label": "Infantry laser", "weight": 2 },
                { "label": "Blast rifle", "weight": 1 },                
            ]
        }
    },
    {
        key: 'specialistweapons',
        title: 'Specialist Weapons',
        sequence: ["weaponA", "weaponB", "weaponC"],
        tables: {
            weaponA: [
                { "label": "Power Claw", "weight": 1 },
                { "label": "Shotgun", "weight": 1 },
                { "label": "Auto rifle", "weight": 1 },
                { "label": "Clingfire pistol", "weight": 1 },
                { "label": "Hunting rifle", "weight": 1 },
                { "label": "Hand gun + Ripper sword", "weight": 1 },
            ],
            weaponB: [
                { "label": "Marksman's rifle", "weight": 1 },
                { "label": "Auto rifle", "weight": 1 },
                { "label": "Shell gun", "weight": 1 },
                { "label": "Hand flamer", "weight": 1 },
                { "label": "Rattle gun", "weight": 2 },
            ],
            weaponC: [
                { "label": "Marksman's rifle", "weight": 1 },                
                { "label": "Shell gun", "weight": 1 },
                { "label": "Fury rifle", "weight": 1 },
                { "label": "Plasma rifle", "weight": 2 },
                { "label": "Hyper blaster", "weight": 1 },               
            ]
        }
    },
]